Repository medical-physics-usz/z-rad, pull requests merged in 2024-10, with the labels that each got.

#139 Implemented union mask calculation
  zrad/__init__.py
  zrad/gui/prep_tab.py
  zrad/gui/rad_tab.py
Labels: enhancement

#142 FIX Move mask validation check before feature extraction
  zrad/logic/radiomics.py
Labels: bug

#144 Renamed Resampling tab, parameter removed from the Preproc. class
  main.py
  zrad/gui/prep_tab.py
  zrad/logic/preprocessing.py
Labels: refactoring

#145 Reduced dicom read actions and added a progress bar in the console
  README.md
  pyproject.toml
  requirements.txt
  zrad/gui/_base_tab.py
  zrad/gui/filt_tab.py
  zrad/gui/prep_tab.py
  zrad/gui/rad_tab.py
  zrad/logic/image.py
  zrad/logic/toolbox_logic.py
Labels: enhancement

#146 Radiomic features renamed in agreement with IBSI
  zrad/logic/radiomics.py
Labels: refactoring

#140 SUV conversion for the GML units
  zrad/logic/image.py
Labels: enhancement

#147 FIX Various minor bugfixes
  zrad/gui/filt_tab.py
  zrad/gui/prep_tab.py
  zrad/gui/rad_tab.py
  zrad/logic/toolbox_logic.py
Labels: bug
