Repository medical-physics-usz/z-rad, pull requests merged in 2024-09, with the labels that each got.

#135 Revisions for PyPI
  README.md
  main.py
  pyproject.toml
  zrad/__init__.py
Labels: enhancement

#137 Refactor: Remove unnecessary PET file flipping and update deprecated pydicom.read_file to pydicom.dcmread
  zrad/logic/image.py
Labels: refactoring

#138 Fix: Changed default mask interpolation threshold when using NN to 0.5
  zrad/gui/prep_tab.py
Labels: bug
