Repository medical-physics-usz/z-rad, pull requests merged in 2025-01, with the labels that each got.

#149 Basic tests
  requirements.txt
  tests/test_IBSI_I.py
  zrad/radiomics/radiomics.py
Labels: enhancement

#156 ENH Packaging and publishing improvements
  .github/workflows/publish.yml
  pyproject.toml
  zrad/__init__.py
Labels: enhancement

#157 ENH Added a GUI screenshot to README
  README.md
  doc/images/zrad_screenshot.png
Labels: enhancement

#158 FIX Conditionally Add RTSTRUCT Path to Preprocessing Parameters
  zrad/gui/prep_tab.py
Labels: bug

#162 FIX for radiomics.py
  zrad/radiomics/radiomics.py
Labels: bug

#160 ENH Added GitHub Actions for automated testing
  .github/workflows/test.yml
  pytest.ini
  tests/test_filtering.py
  tests/test_ibsi_1.py
  tests/test_preprocessing.py
Labels: enhancement

#165 Update publish.yml
  .github/workflows/publish.yml
Labels: refactoring

#167 CI Added missing tests for IBSI I
  tests/test_ibsi_1.py
Labels: CI/CD

#166 REF Improved radiomics calculation speed
  zrad/radiomics/radiomics_definitions.py
Labels: refactoring

#168 CI Add Dependabot for automated dependency updates
  .github/dependabot.yml
Labels: CI/CD
